package com.sun366.entity;

// Generated 2015-4-29 17:41:08 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "sun366")
public class Course implements java.io.Serializable {

	private String id;
	private String teaId;

	public Course() {
	}

	public Course(String id) {
		this.id = id;
	}

	public Course(String id, String teaId) {
		this.id = id;
		this.teaId = teaId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "tea_id", length = 32)
	public String getTeaId() {
		return this.teaId;
	}

	public void setTeaId(String teaId) {
		this.teaId = teaId;
	}

}
