package com.sun366.entity;

// Generated 2015-4-29 17:41:08 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Details generated by hbm2java
 */
@Entity
@Table(name = "details", catalog = "sun366")
public class Details implements java.io.Serializable {

	private String id;
	private String teaId;
	private String realname;
	private String gender;
	private Date birthday;
	private String nickname;
	private String role;
	private String degree;
	private String school;
	private String major;
	private Integer seniority;
	private String organization;
	private String feature;
	private Date modified;

	public Details() {
	}

	public Details(String id) {
		this.id = id;
	}

	public Details(String id, String teaId, String realname, String gender,
			Date birthday, String nickname, String role, String degree,
			String school, String major, Integer seniority,
			String organization, String feature, Date modified) {
		this.id = id;
		this.teaId = teaId;
		this.realname = realname;
		this.gender = gender;
		this.birthday = birthday;
		this.nickname = nickname;
		this.role = role;
		this.degree = degree;
		this.school = school;
		this.major = major;
		this.seniority = seniority;
		this.organization = organization;
		this.feature = feature;
		this.modified = modified;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "tea_id", length = 32)
	public String getTeaId() {
		return this.teaId;
	}

	public void setTeaId(String teaId) {
		this.teaId = teaId;
	}

	@Column(name = "realname", length = 64)
	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	@Column(name = "gender", length = 2)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "nickname", length = 128)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "role", length = 3)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "degree", length = 3)
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	@Column(name = "school", length = 64)
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "major", length = 128)
	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	@Column(name = "seniority")
	public Integer getSeniority() {
		return this.seniority;
	}

	public void setSeniority(Integer seniority) {
		this.seniority = seniority;
	}

	@Column(name = "organization", length = 128)
	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	@Column(name = "feature", length = 128)
	public String getFeature() {
		return this.feature;
	}

	public void setFeature(String feature) {
		this.feature = feature;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

}
