package com.sun366.entity;

// Generated 2015-4-29 17:41:08 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Experience generated by hbm2java
 */
@Entity
@Table(name = "experience", catalog = "sun366")
public class Experience implements java.io.Serializable {

	private int id;
	private String teaId;
	private Date startTime;
	private Date endTime;
	private String describe;
	private Date modified;

	public Experience() {
	}

	public Experience(int id) {
		this.id = id;
	}

	public Experience(int id, String teaId, Date startTime, Date endTime,
			String describe, Date modified) {
		this.id = id;
		this.teaId = teaId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.describe = describe;
		this.modified = modified;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tea_id", length = 32)
	public String getTeaId() {
		return this.teaId;
	}

	public void setTeaId(String teaId) {
		this.teaId = teaId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_time", length = 10)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_time", length = 10)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "describe", length = 2048)
	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

}
